import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import { StoreProvider } from "@/store/slices/StoreProvider";
import { WebSocketProvider } from "@/components/WebSocketProvider";
import AuthProvider from "@/components/auth/AuthProvider";
import UserHeader from "@/components/layout/UserHeader";
import './globals.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50 dark:bg-black`}
      >
        <Providers>
          <StoreProvider>
            <AuthProvider>
              <WebSocketProvider>
                <div className="min-h-screen flex flex-col mx-4">
                  {/* <UserHeader /> */}
                  <main className="flex-1 w-full max-w-10xl mx-auto">
                    {children}
                  </main>
                </div>
              </WebSocketProvider>
            </AuthProvider>
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}
